version: '3.3'

services:
  dtz_master_controller:
    image: 127.0.0.1:5001/dtz_master_controller
    build: src/
#    env_file:
#      - .env
    ports:
      - "4840:4840"
    deploy:
      placement:
        constraints: [node.role == worker]
      resources:
        limits:
          cpus: "1"
          memory: 1G
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

